name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step converts your repo name to lowercase and saves it as an environment variable
      - name: Lowercase Repo Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # We use the new lowercase variable here instead
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview, cves
          image: ghcr.io/${{ env.IMAGE_NAME }}:latest
